artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingenstion
  source_URL: https://github.com/vasaniprince/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  local_fata_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion